# Generated by Django 6.0.3 on 2026-04-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='events_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer_role',
            field=models.CharField(blank=True, choices=[('mobilizer', 'Mobilizer'), ('ward_coordinator', 'Ward Coordinator'), ('polling_agent', 'Polling Agent'), ('data_collector', 'Data Collector'), ('observer', 'Observer')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
    ]
