# Generated by Django 5.1.6 on 2026-05-03 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_contactmessage_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='attempts',
        ),
        migrations.AddField(
            model_name='task',
            name='feedback_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='feedback_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='otp_hash',
            field=models.CharField(max_length=255),
        ),
    ]
